#
# Master Bedroom
#

- platform: mqtt
  name: "Master Bedoom Light"
  state_topic: "smartthings/Master Bedroom Light/switch"
  command_topic: "smartthings/Master Bedroom Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true # keep device in sync when things are disconnected