#
# Office Room
#

- platform: mqtt
  name: "Office Room Light"
  state_topic: "smartthings/Office Room Light/switch"
  command_topic: "smartthings/Office Room Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true # keep device in sync when things are disconnected
