#
# configuration.yaml
# Core configuration file
#

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 90
  unit_system: metric
  time_zone: !secret timezone

http:
  api_password: !secret http_password

frontend:

updater:
  reporting: no

sun:
  elevation: !secret elevation

#
# Components
#

discovery:

apple_tv:

cloud:
  mode: development
  cognito_client_id: !secret cloud_client_id
  user_pool_id: !secret cloud_user_pool_id
  region: !secret cloud_region
  relayer: !secret cloud_relayer

mqtt:
  broker: !secret mqtt_broker

lutron_caseta:
  host: !secret lutron_ip
  keyfile: caseta.key
  certfile: caseta.crt
  ca_certs: caseta-bridge.crt

nest:
  client_id: !secret nest_username
  client_secret: !secret nest_password

ecobee:
  api_key: !secret ecobee_api
  hold_temp: False

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

wemo:
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip
    - !secret wemo3_ip
    - !secret wemo4_ip
    - !secret wemo5_ip

zeroconf:

#
# Sensors
#

sensor: !include_dir_merge_list sensors

#
# MQTT Light Switches (From SmartThings)
#

switch: !include_dir_merge_list switches

#
# Device Groups
#

group: !include group.yaml

#
# Custom Inputs
#

input_boolean:

  guest_mode:
    name: Guest Mode
    initial: off

  goodnight:
    name: Goodnight
    initial: off

#
# Scenes
#

scene: !include scenes.yaml

#
# Logging + Notifications
#

# Notifications
notify: !include notify.yaml

# Logging to InfluxDB
# influxdb:
#   host: !secret influx_host
#   exclude:
#     domains:
#       - automation
