\#
# configuration.yaml
# Core configuration file
#

homeassistant:
  name: Home
  latitude: !secret latitude # Moved to secret March 6, 2017
  longitude: !secret longitude # Moved to secret March 6, 2017
  unit_system: metric
  time_zone: America/Toronto

frontend:

updater: # Enabled Jul 6, 2016
  reporting: no # Added Dec 26, 2016

discovery:

mqtt:
  broker: !secret mqtt-broker

sun:
  elevation: 91
